import { AppState, Preset } from './types';

export const OPTIONS = {
  cabinetDoor: [
    'MDF Melamine mờ',
    'PET siêu mờ',
    'Acrylic bóng'
  ],
  cabinetColor: [
    'Màu Cơ Bản - Trắng sứ',
    'Màu Cơ Bản - Ghi sáng',
    'Màu Cơ Bản - Xám đậm',
    'Màu Cơ Bản - Đen nhám',
    'Màu Cơ Bản - Vân gỗ sồi',
    'Màu Cơ Bản - Vân gỗ óc chó',
    'Màu Cơ Bản - Xanh navy mờ',
    'Màu Cơ Bản - Be',
    'ALD AC 02* - Độ bóng cao - #DBDADB',
    'ALD AC 04 - Độ bóng cao - #E5E3DB',
    'ALD AC 05 - Cappuccino - Độ bóng cao - #A88665',
    'ALD AC 06 - Anthracite Grey - Độ bóng cao - #4F555A',
    'ALD AC 07 - Độ bóng cao - #B5171C',
    'ALD AC 08 - Royal Red - Độ bóng cao - #6E1114',
    'ALD AC 09 - Bordeaux - Độ bóng cao - #43080A',
    'ALD AC 10 - Beige - Độ bóng cao - #C6B39C',
    'ALD AC 11 - Độ bóng cao - #9EA9B1',
    'ALD AC 12 - Vanilla - Độ bóng cao - #D0CBBF',
    'ALD AC 13 - Sand - Độ bóng cao - #ABA598',
    'ALD AC 14 - Lime Green - Độ bóng cao - #BAD66C',
    'ALD AC 15 - Độ bóng cao - #88C43E',
    'ALD AC 17 - Wine Metallic - Độ bóng cao - #0D0607',
    'ALD AC 18 - Độ bóng cao - #8C9298',
    'ALD AC 19 - Độ bóng cao - #271A15',
    'ALD AC 21 - Độ bóng cao - #0A0A0A',
    'ALD AC 22* - Chocolate Oak (Sồi nâu socola) - Độ bóng cao - #927C6A',
    'ALD AC 23* - Oak (Sồi nâu hạt dẻ) - Độ bóng cao - #A68A71',
    'ALD AC 26 - Champagne - Độ bóng cao - #B5B099',
    'ALD AC 27 - Mocha - Độ bóng cao - #937B67',
    'ALD AC 28 - Pearl Latte - Độ bóng cao - #878A77',
    'ALD AC 29 - Độ bóng cao - #4F5257',
    'ALD AC 30 - Oak (Sồi vàng nâu) - Độ bóng cao - #462F1F',
    'ALD AC 31** - Độ bóng cao - #C7C8CA',
    'ALD AC 32 - Dark Wood (Gỗ tối màu, vân cuộn) - Độ bóng cao - #311F16',
    'ALD AC 33* - Độ bóng cao - #D7DADC',
    'ALD AC 34 - Lime (Gỗ Tây Ban Nha) - Độ bóng cao - #875C36',
    'ALD AC 35 - Stone Black (Đá đen đá phiến) - Độ bóng cao - #1A1C1D',
    'ALD AC 36 - Độ bóng cao - #4E4237',
    'ALD AC 37 - Pearl Iron - Độ bóng cao - #767D85',
    'ALD AC 38** - Độ bóng cao - #595F64',
    'ALD AC 39** - Độ bóng cao - #DFDFDF',
    'ALD AC 41 - Pearl Gold - Độ bóng cao - #EAB200',
    'ALD AC 47 - Zeb Wood (Vân ngựa vằn) - Độ bóng cao - #9A7251',
    'ALD AC 50 - Champagne Metallic - Độ bóng cao - #9B9B96',
    'ALD AC 51** - Độ bóng cao - #929699',
    'ALD AC 52 - Mocca - Độ bóng cao - #86796A',
    'ALD AC 54 - Magnesium (Giả đá kim loại xám) - Độ bóng cao - #4B4E52',
    'ALD AC 55** - Capuchino Pearl - Độ bóng cao - #8F8175',
    'ALD AC 56 - Oak (Sồi vàng đậm) - Độ bóng cao - #533C2D',
    'ALD AC 58 - Lyon (Sồi vàng nâu kiểu Á) - Độ bóng cao - #C8AC8F',
    'ALD AC 59 - Độ bóng cao - #1D567E',
    'ALD AC 60 - Dark Oak (Sồi đen sâu Ý) - Độ bóng cao - #2D231E',
    'ALD AC 61 - Cobalt - Độ bóng cao - #063960',
    'ALD AC 62 - Brushed Anthracite (Than chì xước) - Độ bóng cao - #080808',
    'ALD AC 65 - Black Wood (Gỗ đen tuyền) - Độ bóng cao - #161616',
    'ALD AC 66 - Beige Metallic - Độ bóng cao - #C5C6C1',
    'ALD AC 67 - Độ bóng cao - #0A0A0A',
    'ALD AC 68 - Rovere Oak (Sồi trắng ngà) - Độ bóng cao - #CDBDAE',
    'ALD AC 69 - Rovere (Sồi nâu đỏ) - Độ bóng cao - #624A3A',
    'ALD AC 70 - Gris Ebony (Mun xám đen) - Độ bóng cao - #70503B',
    'ALD AC 71 - Brushed Aluminium (Nhôm xước bạc) - Độ bóng cao - #848588',
    'ALD AC 72** - Độ bóng cao - #7C95A2',
    'ALD AC 73** - Độ bóng cao - #637678',
    'ALD AC 75** - Độ bóng cao - #68809A',
    'ALD AC 76** - Độ bóng cao - #78726A',
    'ALD AC 78 - Pica Green - Độ bóng cao - #16A5C2',
    'ALD AC 79 - Tortora - Độ bóng cao - #A29381',
    'ALD AC 80 - Rose Gold - Độ bóng cao - #7A5B51',
    'ALD AC 81 - Tigerwood (Gỗ hổ nâu xám) - Độ bóng cao - #959695',
    'ALD AC 82 - Tigerwoodwhite (Vân gỗ hổ trắng) - Độ bóng cao - #E0E0DF',
    'ALD AC 83 - Marquinia (Đá đen vân mây trắng) - Độ bóng cao - #2A2A2C',
    'ALD AC 84 - Mazzi Tortora (Giả đá vôi xám nhạt) - Độ bóng cao - #D0CBBF',
    'ALD AC 85 - Classico Grigio (Đá xám cổ điển) - Độ bóng cao - #D8D4CA',
    'ALD AC 87 - Misty Mira (Giả đá mù sương) - Độ bóng cao - #7C7D7F',
    'ALD AC 90 - Oro Metallic (Gỗ ánh kim đồng) - Độ bóng cao - #543D32',
    'ALD AC 91 - Vintage Mira (Gỗ cổ điển, vàng rêu) - Độ bóng cao - #84734B',
    'ALD AC 92 - Lavato Oak (Sồi Ý trắng sáng) - Độ bóng cao - #D2C8BC',
    'ALD AC 93 - Ebony (Gỗ mun đen Ý) - Độ bóng cao - #1A1918',
    'ALD AC 94 - Pink - Độ bóng cao - #D6A4B8',
    'ALD AC 96 - Marble (Đá cẩm thạch trắng) - Độ bóng cao - #E8ECEE',
    'ALD AC 97 - Độ bóng cao - #73A0C2',
    'ALD AC 98 - Sky Blue - Độ bóng cao - #67B8D6',
    'ALD AC 103 - Độ bóng cao - #8B98A3',
    'ALD AC 105 - Brown Oak (Sồi nâu đất) - Độ bóng cao - #55351E',
    'ALD AC 106 - Rovere Oak (Sồi vàng sáng) - Độ bóng cao - #D09E6D',
    'ALD AC 108 - Vani Cream - Độ bóng cao - #CEC1AA',
    'ALD AC 109 - Dusk - Độ bóng cao - #383838',
    'ALD AC 110 - Độ bóng cao - #4B535A',
    'ALD AC 111** - Violet - Độ bóng cao - #230B17',
    'ALD AC 112 - Mocca - Độ bóng cao - #979391',
    'ALD AC 113 - Độ bóng cao - #B0B9C0',
    'ALD AC 115 - Misty - Độ bóng cao - #8E918E',
    'ALD AC 116 - Hazelnut - Độ bóng cao - #B3A899',
    'ALD AC 117 - Navy - Độ bóng cao - #0A536A',
    'ALD AC 118 - Độ bóng cao - #B9B5B2',
    'ALD AC 119 - Gris - Độ bóng cao - #82847A',
    'ALD AC 120 - Dust Grey - Độ bóng cao - #5C6267',
    'ALD AC 121** - Pearl Iron Matt - Độ bóng cao - #4B555F',
    'ALD AC 122** - Gold Metallic Matt - Độ bóng cao - #9B8E71',
    'ALD AC 123** - Grey Metallic Matt - Độ bóng cao - #3E3F42',
    'ALD AE 03** - Độ bóng cao - #D3D8DD',
    'ALD ZENA 01 - Độ bóng cao - #D9DBDF',
    'ALD ZENA 02 - Độ bóng cao - #A8CDD2',
    'ALD ZENA 03 - Cream Capuchino 2mm - Độ bóng cao - #B6A8A0',
    'ALD AC 31 ** - Pearl White - Austria - Độ bóng cao - #C7C8CA',
    'ALD AC 39 ** - Cream White Metallic - Austria - Độ bóng cao - #DFDFDF',
    'ALD AC 72 ** - Blue Metallic - Austria - Độ bóng cao - #7C95A2',
    'ALD AC 38 ** - Silver Metallic - Austria - Độ bóng cao - #595F64',
    'ALD AC 76 ** - Gold Metallic - Austria - Độ bóng cao - #9D917D',
    'ALD AC 77 ** - Copper Metallic - Austria - Độ bóng cao - #8C756A',
    'ALD AC 04 - Pearl cream white - Độ bóng cao - #E5E3DB',
    'ALD AC 18 - Độ bóng cao - #8C9298',
    'ALD AC 29 - Độ bóng cao - #4F5257',
    'ALD AC 36 - Độ bóng cao - #4E4237',
    'ALD AC 41 - Pearl Gold - Độ bóng cao - #EAB200',
    'ALD AC 42 - Pearl Copper - Độ bóng cao - #B46A42',
    'ALD AC 43 - Pearl Red - Độ bóng cao - #93272C',
    'ALD AC 44 - Pearl Blue - Độ bóng cao - #334A66',
    'ALD AC 45 - Pearl Green - Độ bóng cao - #4A6B53',
    'ALD AC 46 - Pearl Black - Độ bóng cao - #1A1A1A',
    'MDF & MELAMIN - MS 021 T - Màu hồng phấn nhạt - #F4B7BD',
    'MDF & MELAMIN - MS 024 LU - Xanh Sage nhạt - #B8C0AE',
    'MDF & MELAMIN - MS 024 MM - Xanh Sage nhạt, bề mặt mờ - #C7CDBB',
    'MDF & MELAMIN - MS 024 SMM - Xanh Sage nhạt, bề mặt siêu mờ - #D2D6C7',
    'MDF & MELAMIN - MS 025 LU - Màu xám nâu - #837A6B',
    'MDF & MELAMIN - MS 025 MM - Màu xám nâu, bề mặt mờ - #928A7D',
    'MDF & MELAMIN - MS 025 SMM - Màu xám nâu, bề mặt siêu mờ - #9B9185',
    'MDF & MELAMIN - MS 027 T - Màu đỏ tươi - #BF0A1B',
    'MDF & MELAMIN - MS 030 PL - Màu vàng mù tạt - #D8B031',
    'MDF & MELAMIN - MS 030 SH - Màu vàng nghệ - #F6CD4F',
    'MDF & MELAMIN - MS 031 WN - Vân gỗ Óc chó, tông nâu ấm - #915D3C',
    'MDF & MELAMIN - MS 032 T - Màu vàng sáng - #F2C94F',
    'MDF & MELAMIN - MS 041 T - Màu cam - #F68F2E',
    'MDF & MELAMIN - MS 050 T - Màu xanh da trời nhạt - #87B0D1',
    'MDF & MELAMIN - MS 073 T - Màu xanh lá mạ - #B6CD5C',
    'MDF & MELAMIN - MS 074 T - Màu xanh lá cây đậm - #548E1D',
    'MDF & MELAMIN - MS 083 T - Màu xanh Navy đậm - #0B2447',
    'MDF & MELAMIN - MS 101 FL - Màu trắng sứ - #FDFDFD',
    'MDF & MELAMIN - MS 101 LU - Trắng xám nhẹ - #EEEDE9',
    'MDF & MELAMIN - MS 101 MM - Màu trắng mờ - #FDFDFD',
    'MDF & MELAMIN - MS 101 PL - Màu trắng xám - #E1E1DE',
    'MDF & MELAMIN - MS 101 SH - Màu trắng tiêu chuẩn - #FDFDFD',
    'MDF & MELAMIN - MS 101 SMM - Trắng siêu mờ - #FDFDFD',
    'MDF & MELAMIN - MS 101 T - Trắng sần nhẹ - #FDFDFD',
    'MDF & MELAMIN - MS 103 MM - Màu xám nhạt - #D9DAD7',
    'MDF & MELAMIN - MS 103 SMM - Màu xám nhạt mịn - #DDE0DE',
    'MDF & MELAMIN - MS 103 T - Màu xám trắng - #E0E2E3',
    'MDF & MELAMIN - MS 104 LU - Màu trắng gương - #FDFDFD',
    'MDF & MELAMIN - MS 104 MM - Màu trắng trung tính - #FDFDFD',
    'MDF & MELAMIN - MS 105 G - Màu xám xi măng nhạt - #D8D9D7',
    'MDF & MELAMIN - MS 106 MM - Màu kem nhạt - #EAEAE2',
    'MDF & MELAMIN - MS 106 PL - Màu kem sữa - #E9E6D8',
    'MDF & MELAMIN - MS 107 SMM - Màu xanh xám băng - #E1E6EB',
    'MDF & MELAMIN - MS 120 PL - Màu xám than - #3E4145',
    'MDF & MELAMIN - MS 201 LU - Màu đen xám đậm - #333333',
    'MDF & MELAMIN - MS 203 LU - Màu xám trung tính - #8E8E8E',
    'MDF & MELAMIN - MS 212 LU - Màu xanh rêu nhạt - #94A69E',
    'MDF & MELAMIN - MS 215 LU - Màu xanh đá đậm - #3C4E5E',
    'MDF & MELAMIN - MS 216 LU - Màu xanh rêu quân đội - #555D36',
    'MDF & MELAMIN - MS 217 LU - Màu nâu xám ấm - #8D7E70',
    'MDF & MELAMIN - MS 220-1 LU - Màu Beige cát - #B8A88E',
    'MDF & MELAMIN - MS 222 LU - Màu hồng đất - #B68D7D',
    'MDF & MELAMIN - MFC - MS 303',
    'MDF & MELAMIN - MFC - MS 309',
    'MDF & MELAMIN - MFC - MS 323',
    'MDF & MELAMIN - MFC - MS 324',
    'MDF & MELAMIN - MFC - MS 325',
    'MDF & MELAMIN - MFC - MS 328',
    'MDF & MELAMIN - MFC - MS 329',
    'MDF & MELAMIN - MFC - MS 330',
    'MDF & MELAMIN - MFC - MS 331',
    'MDF & MELAMIN - MFC - MS 332',
    'MDF & MELAMIN - MFC - MS 333',
    'MDF & MELAMIN - MFC - MS 334',
    'MDF & MELAMIN - MFC - MS 335',
    'MDF & MELAMIN - MFC - MS 336',
    'MDF & MELAMIN - MFC - MS 337',
    'MDF & MELAMIN - MFC - MS 338',
    'MDF & MELAMIN - MFC - MS 340',
    'MDF & MELAMIN - MFC - MS 341',
    'MDF & MELAMIN - MFC - MS 347',
    'MDF & MELAMIN - MFC - MS 368',
    'MDF & MELAMIN - MFC - MS 376',
    'MDF & MELAMIN - MFC - MS 379',
    'MDF & MELAMIN - MFC - MS 383',
    'MDF & MELAMIN - MFC - MS 384',
    'MDF & MELAMIN - MFC - MS 385',
    'MDF & MELAMIN - MFC - MS 386',
    'MDF & MELAMIN - MFC - MS 388',
    'MDF & MELAMIN - MFC - MS 389',
    'MDF & MELAMIN - MFC - MS 390',
    'MDF & MELAMIN - MFC - MS 401',
    'MDF & MELAMIN - MFC - MS 402',
    'MDF & MELAMIN - MFC - MS 403',
    'MDF & MELAMIN - MFC - MS 404',
    'MDF & MELAMIN - MFC - MS 405',
    'MDF & MELAMIN - MFC - MS 406',
    'MDF & MELAMIN - MFC - MS 407',
    'MDF & MELAMIN - MFC - MS 408',
    'MDF & MELAMIN - MFC - MS 409',
    'MDF & MELAMIN - MFC - MS 410',
    'MDF & MELAMIN - MFC - MS 411',
    'MDF & MELAMIN - MFC - MS 412',
    'MDF & MELAMIN - MFC - MS 413',
    'MDF & MELAMIN - MFC - MS 414',
    'MDF & MELAMIN - MFC - MS 415',
    'MDF & MELAMIN - MFC - MS 416',
    'MDF & MELAMIN - MFC - MS 417',
    'MDF & MELAMIN - MFC - MS 418',
    'MDF & MELAMIN - MFC - MS 419',
    'MDF & MELAMIN - MFC - MS 420',
    'MDF & MELAMIN - MFC - MS 421',
    'MDF & MELAMIN - MFC - MS 422',
    'MDF & MELAMIN - MFC - MS 423',
    'MDF & MELAMIN - MFC - MS 424',
    'MDF & MELAMIN - MFC - MS 425',
    'MDF & MELAMIN - MFC - MS 426',
    'MDF & MELAMIN - MFC - MS 427',
    'MDF & MELAMIN - MFC - MS 428',
    'MDF & MELAMIN - MFC - MS 429',
    'MDF & MELAMIN - MFC - MS 430',
    'MDF & MELAMIN - MFC - MS 431',
    'MDF & MELAMIN - MFC - MS 432',
    'MDF & MELAMIN - MFC - MS 433',
    'MDF & MELAMIN - MFC - MS 434',
    'MDF & MELAMIN - MFC - MS 435',
    'MDF & MELAMIN - MFC - MS 436',
    'MDF & MELAMIN - MFC - MS 437',
    'MDF & MELAMIN - MFC - MS 439',
    'MDF & MELAMIN - MFC - MS 440',
    'MDF & MELAMIN - MFC - MS 441',
    'MDF & MELAMIN - MFC - MS 442',
    'MDF & MELAMIN - MFC - MS 443',
    'MDF & MELAMIN - MFC - MS 444',
    'MDF & MELAMIN - MFC - MS 445',
    'MDF & MELAMIN - MFC - MS 446',
    'MDF & MELAMIN - MFC - MS 447',
    'MDF & MELAMIN - MFC - MS 448',
    'MDF & MELAMIN - MFC - MS 449',
    'MDF & MELAMIN - MFC - MS 450',
    'MDF & MELAMIN - MFC - MS 451',
    'MDF & MELAMIN - MFC - MS 452',
    'MDF & MELAMIN - MFC - MS 453',
    'MDF & MELAMIN - MFC - MS 454',
    'MDF & MELAMIN - MFC - MS 455',
    'MDF & MELAMIN - MFC - MS 456',
    'MDF & MELAMIN - MFC - MS 457',
    'MDF & MELAMIN - MFC - MS 458',
    'MDF & MELAMIN - MFC - MS 459',
    'MDF & MELAMIN - MFC - MS 460',
    'MDF & MELAMIN - MFC - MS 461',
    'MDF & MELAMIN - MFC - MS 462',
    'MDF & MELAMIN - MFC - MS 463',
    'MDF & MELAMIN - MFC - MS 464',
    'MDF & MELAMIN - MFC - MS 465',
    'MDF & MELAMIN - MFC - MS 466',
    'MDF & MELAMIN - MFC - MS 467',
    'MDF & MELAMIN - MFC - MS 468',
    'MDF & MELAMIN - MFC - MS 469',
    'MDF & MELAMIN - MFC - MS 470',
    'MDF & MELAMIN - MFC - MS 471',
    'MDF & MELAMIN - MFC - MS 472',
    'MDF & MELAMIN - MFC - MS 473',
    'MDF & MELAMIN - MFC - MS 474',
    'MDF & MELAMIN - MFC - MS 475',
    'MDF & MELAMIN - MFC - MS 476',
    'MDF & MELAMIN - MFC - MS 477',
    'MDF & MELAMIN - MFC - MS 478',
    'MDF & MELAMIN - MFC - MS 479',
    'MDF & MELAMIN - MFC - MS 480',
    'MDF & MELAMIN - MFC - MS 481',
    'MDF & MELAMIN - MFC - MS 482',
    'MDF & MELAMIN - MFC - MS 483',
    'MDF & MELAMIN - MFC - MS 501',
    'MDF & MELAMIN - MFC - MS 502',
    'MDF & MELAMIN - MFC - MS 503',
    'MDF & MELAMIN - MFC - MS 504',
    'MDF & MELAMIN - MFC - MS 505',
    'MDF & MELAMIN - MFC - MS 506',
    'MDF & MELAMIN - MFC - MS 507',
    'MDF & MELAMIN - MFC - MS 508',
    'MDF & MELAMIN - MFC - MS 509',
    'MDF & MELAMIN - MFC - MS 511',
    'MDF & MELAMIN - MFC - MS 512',
    'MDF & MELAMIN - MFC - MS 513',
    'MDF & MELAMIN - MFC - MS 514',
    'MDF & MELAMIN - MFC - MS 515',
    'MDF & MELAMIN - MFC - MS 516',
    'MDF & MELAMIN - MFC - MS 517',
    'MDF & MELAMIN - MFC - MS 518',
    'MDF & MELAMIN - MFC - MS 519',
    'MDF & MELAMIN - MFC - MS 520',
    'MDF & MELAMIN - MFC - MS 601',
    'MDF & MELAMIN - MFC - MS 603',
    'MDF & MELAMIN - MFC - MS 604',
    'MDF & MELAMIN - MFC - MS 605',
    'MDF & MELAMIN - MFC - MS 608',
    'MDF & MELAMIN - MFC - MS 609',
    'MDF & MELAMIN - MFC - MS 610',
    'MDF & MELAMIN - MFC - MS 611',
    'MDF & MELAMIN - MFC - MS 612',
    'MDF & MELAMIN - MFC - MS 613',
    'MDF & MELAMIN - MFC - MS 614',
    'MDF & MELAMIN - MFC - MS 619',
    'MDF & MELAMIN - MFC - MS 620',
    'MDF & MELAMIN - MFC - MS 622',
    'MDF & MELAMIN - MFC - MS 623',
    'MDF & MELAMIN - MFC - MS 624',
    'MDF & MELAMIN - MFC - MS 625',
    'MDF & MELAMIN - MFC - MS 626',
    'MDF & MELAMIN - MFC - MS 627',
    'MDF & MELAMIN - MFC - MS 630',
    'MDF & MELAMIN - MFC - MS 631',
    'MDF & MELAMIN - MFC - MS 635',
    'MDF & MELAMIN - MFC - MS 640',
    'MDF & MELAMIN - MFC - MS 641',
    'MDF & MELAMIN - MFC - MS 642',
    'MDF & MELAMIN - MFC - MS 643',
    'MDF & MELAMIN - MFC - MS 644',
    'MDF & MELAMIN - MFC - MS 650',
    'MDF & MELAMIN - MFC - MS 651',
    'MDF & MELAMIN - MFC - MS 699',
    'MDF & MELAMIN - MFC - MS 720',
    'MDF & MELAMIN - MFC - MS 730',
    'MDF & MELAMIN - MFC - MS 739',
    'MDF & MELAMIN - MFC - MS 740',
    'MDF & MELAMIN - MFC - MS 770',
    'MDF & MELAMIN - MFC - MS 771',
    'MDF & MELAMIN - MFC - MS 790',
    'MDF & MELAMIN - MFC - MS 851',
    'MDF & MELAMIN - MFC - MS 852',
    'MDF & MELAMIN - MFC - MS 990',
    'MDF & MELAMIN - MFC - MS 996',
    'MDF & MELAMIN - MFC - MS 998',
    'MDF & MELAMIN - MFC - MS 999',
    'MDF & MELAMIN - MFC - MS 1012',
    'MDF & MELAMIN - MFC - MS 4002',
    'MDF & MELAMIN - MFC - MS 4012',
    'MDF & MELAMIN - MFC - MS 4028',
    'MDF & MELAMIN - MFC - MS 4029',
    'MDF & MELAMIN - MFC - MS 4030',
    'MDF & MELAMIN - MFC - MS 4038',
    'MDF & MELAMIN - MFC - MS 4502',
    'MDF & MELAMIN - MFC - MS 4601',
    'MDF & MELAMIN - MFC - MS 4602',
    'MDF & MELAMIN - MFC - MS 9205',
    'MDF & MELAMIN - MFC - MS 9222',
    'MDF & MELAMIN - MFC - MS 9223',
    'MDF & MELAMIN - MFC - MS 9225',
    'MDF & MELAMIN - MFC - MS 9238',
    'MDF & MELAMIN - MFC - MS 9241',
    'MDF & MELAMIN - MFC - MS 9284',
    'MDF & MELAMIN - MFC - MS 10081',
    'MDF & MELAMIN - MFC - MS 10083',
    'MDF & MELAMIN - MFC - MS 10084',
    'MDF & MELAMIN - MFC - MS LK056',
    'MDF & MELAMIN - MFC - MS LK352',
    'MDF & MELAMIN - MFC - MS LK452',
    'MDF & MELAMIN - MFC - MS LK995',
    'MDF & MELAMIN - MFC - MS LK3106',
    'MDF & MELAMIN - MFC - MS LK4457',
    'MDF & MELAMIN - MFC - MS LK4463',
    'MDF & MELAMIN - MFC - MS LK4501',
    'MDF & MELAMIN - MFC - MS LK4507',
    'MDF & MELAMIN - MFC - MS LK9904'
  ],
  handles: [
    'Không tay nắm / vát cạnh / Gola',
    'Tay nắm âm',
    'Tay nắm núm tròn',
    'Tay nắm thanh dài (Đen)',
    'Tay nắm thanh dài (Vàng)',
    'Tay nắm hiện đại'
  ],
  floor: [
    'Gạch xương sứ vân đá mờ',
    'Sàn gỗ xương cá',
    'Sàn gỗ thẳng',
    'Sàn bê tông mài',
    'Gạch Terrazzo'
  ],
  wall: [
    'Sơn trắng mờ',
    'Sơn xám nhạt',
    'Hiệu ứng bê tông',
    'Giấy dán tường vân vải'
  ],
  style: [
    'Hiện đại',
    'Tối giản',
    'Công nghiệp'
  ],
  lighting: [
    'Ánh sáng tự nhiên ban ngày',
    'Ánh sáng vàng ấm / chiều tà',
    'Ánh sáng đèn LED hắt tủ bếp',
    'Ánh sáng studio dịu nhẹ',
    'Ánh sáng mặt trời chiếu qua rèm'
  ],
  exposure: [
    'Mặc định',
    'Sáng nhẹ (+0.5 EV)',
    'Sáng vừa (+1.0 EV)',
    'Sáng nhiều (+1.5 EV)',
    'Sáng rực rỡ (+2.0 EV)'
  ],
  cameraAngle: [
    'Góc nhìn thẳng',
    'Góc nhìn chéo 45 độ',
    'Góc nhìn từ trên xuống',
    'Cận cảnh vật liệu'
  ],
  renderQuality: [
    'Siêu thực',
    '8k resolution, highly detailed',
    'Unreal Engine 5 render',
    'V-Ray render',
    'Corona render'
  ],
  frameStyle: [
    'Không viền (No frame)',
    'Viền trắng tối giản (Minimalist White)',
    'Viền đen sang trọng (Luxury Black)'
  ],
  ceilingLight: [
    'Đèn LED âm trần',
    'Đèn thả trần hiện đại',
    'Đèn chùm pha lê',
    'Đèn ray nam châm',
    'Đèn ốp trần gỗ'
  ],
  decor: [
    'Cây xanh trang trí',
    'Bình hoa gốm sứ và sách nghệ thuật',
    'Đèn bàn trang trí',
    'Tranh treo tường hiện đại',
    'Tối giản, không đồ trang trí'
  ],
  roomType: [
    'Phòng khách',
    'Phòng ngủ',
    'Phòng ăn',
    'Phòng làm việc',
    'Phòng tắm',
    'Phòng thay đồ (Walk-in Closet)'
  ],
  mainFurnitureMaterial: [
    'Gỗ sồi (Oak)',
    'Gỗ óc chó (Walnut)',
    'Gỗ công nghiệp MDF',
    'Kim loại & Kính',
    'Da & Nỉ',
    'Gỗ sơn bệt'
  ],
  furnitureColor: [
    'Màu trung tính (Neutral)',
    'Màu tối sang trọng (Dark Luxury)',
    'Màu sáng hiện đại (Light Modern)',
    'Màu pastel',
    'Đen & Trắng'
  ],
  sofaOrBedMaterial: [
    'Da thật',
    'Vải nỉ',
    'Nhung',
    'Gỗ tự nhiên',
    'Không có (N/A)'
  ],
  wardrobeSideShelfType: [
    'shelves',
    'hanging',
    'zigzag',
    'drawers',
    'wine',
    'rounded',
    'glass_display',
    'bag_display',
    'vanity',
    'mirror'
  ]
};

export const PRESETS: Preset[] = [
  {
    id: 'modern-bright',
    name: 'Sáng sạch hiện đại',
    state: {
      style: 'Hiện đại',
      cabinetDoor: 'PET siêu mờ',
      handles: 'Không tay nắm / vát cạnh / Gola',
      floor: 'Gạch xương sứ vân đá mờ',
      wall: 'Sơn trắng mờ',
      ceilingLight: 'Đèn LED âm trần',
      lighting: 'Ánh sáng tự nhiên ban ngày',
      exposure: 'Sáng vừa (+1.0 EV)',
      cameraAngle: 'Góc nhìn chéo 45 độ',
      renderQuality: 'Siêu thực',
      realisticMaterials: true
    }
  },
  {
    id: 'luxury-dark',
    name: 'Đen trắng sang trọng',
    state: {
      style: 'Tối giản',
      cabinetDoor: 'MDF Melamine mờ',
      handles: 'Tay nắm đen nhám',
      floor: 'Sàn bê tông mài',
      wall: 'Sơn xám nhạt',
      ceilingLight: 'Đèn ray nam châm',
      lighting: 'Ánh sáng studio dịu nhẹ',
      exposure: 'Mặc định',
      cameraAngle: 'Góc nhìn thẳng',
      renderQuality: '8k resolution, highly detailed',
      realisticMaterials: true
    }
  }
];

export const DEFAULT_LOGO = "/logo.jpg";

export const DEFAULT_STATE: AppState = {
  activeTab: 'design',
  renderMode: 'interior',
  originalImage: null,
  cabinetDoor: 'Acrylic bóng',
  referenceImage: null,
  handles: 'Không tay nắm / vát cạnh / Gola',
  floor: 'Gạch xương sứ vân đá mờ',
  wall: 'Sơn trắng mờ',
  ceilingLight: 'Đèn LED âm trần',
  decor: 'Trái cây tươi và thớt gỗ',
  style: 'Công nghiệp',
  lighting: 'Ánh sáng studio dịu nhẹ',
  exposure: 'Sáng rực rỡ (+2.0 EV)',
  cameraAngle: '',
  renderQuality: 'V-Ray render',
  notes: '',
  companyLogo: null,
  logoType: 'none',
  projectName: '',
  frameStyle: 'Viền trắng tối giản (Minimalist White)',
  realisticMaterials: true,
  renderIncludeCabinetDoors: true,
  lowerCabinetColor: 'Màu trung tính (Neutral)',
  upperCabinetColor: 'Màu trung tính (Neutral)',
  lowerCabinetImage: null,
  upperCabinetImage: null,
  renderIncludeUpperCabinets: true,
  renderIncludeLowerCabinets: true,
  roomType: 'Phòng khách',
  mainFurnitureMaterial: 'Gỗ sồi (Oak)',
  furnitureColor: 'Màu trung tính (Neutral)',
  sofaOrBedMaterial: 'Vải nỉ',
  // Wardrobe Design
  wardrobeLength: '',
  wardrobeHeight: '2400',
  wardrobeDepth: '600',
  wardrobeNumWings: '',
  wardrobeHasTopBlock: false,
  wardrobeIsCeilingHeight: true,
  wardrobeHideDoors: false,
  wardrobeShiftDoors: true,
  wardrobeShowInternalBlocks: false,
  wardrobeAnalysisResult: null,
  wardrobeAnalysisData: null,
  wardrobeCeilingAdjustment: 0,
  wardrobeSideShelfLeftEnabled: false,
  wardrobeSideShelfLeftWidth: '400',
  wardrobeSideShelfLeftCategory: 'internal',
  wardrobeSideShelfLeftType: 'shelves',
  wardrobeSideShelfLeftSpacing: '400',
  wardrobeSideShelfLeftExternalType: 'left',
  wardrobeSideShelfRightEnabled: false,
  wardrobeSideShelfRightWidth: '400',
  wardrobeSideShelfRightCategory: 'internal',
  wardrobeSideShelfRightType: 'shelves',
  wardrobeSideShelfRightSpacing: '400',
  wardrobeSideShelfRightExternalType: 'right',
  wardrobeSideShelfExternalCodes: {
    'left': '# Model ngoài bên trái',
    'right': '# Model ngoài bên phải'
  },
  wardrobeSideShelfExternalPaths: {
    'left': '',
    'right': ''
  },
  wardrobeExternalBaseDir: 'D:\\AI APP SKETCHUP\\MAP MÀU\\AN CƯỜNG',
  wardrobeModelBaseDir: 'D:\\AI APP SKETCHUP\\DC KỆ TỦ ÁO\\H2400',
  wardrobeAccordionOpen: true,
  wardrobeColorMapPath: '',
  wardrobeBoxColorMapPath: '',
  wardrobeDoorColorMapPath: '',
  wardrobeShelfColorMapPath: '',
  wardrobeSameColor: true,
  wardrobeAllSameColor: true,
  wardrobeApplyMaterials: false,
  wardrobeFullDoors: false,
  wardrobeExportFullDoors: false,
  wardrobeExportShiftDoors: false,
  wardrobeExportView3DLeft: true,
  wardrobeExportView3DRight: false,
  wardrobeExportViewFront: true,
  wardrobeExportViewSideLeft: false,
  wardrobeExportViewSideRight: false,
  wardrobeExportViewTop: false,
  wardrobeColorBrand: 'An Cường',
  wardrobeAdvancedFeaturesOpen: false,
  customerName: '',
  customerPhone: '',
  customerAddress: '',
  exportVersion: 0,
};

export const AN_CUONG_COLORS = [
  "MFC - MS 021 T", "MFC - MS 024 LU", "MFC - MS 024 MM", "MFC - MS 024 SMM",
  "MFC - MS 025 LU", "MFC - MS 025 MM", "MFC - MS 025 SMM", "MFC - MS 027 T",
  "MFC - MS 030 PL", "MFC - MS 030 SH", "MFC - MS 031 WN", "MFC - MS 032 T",
  "MFC - MS 041 T", "MFC - MS 050 T", "MFC - MS 073 T", "MFC - MS 074 T",
  "MFC - MS 083 T", "MFC - MS 101 FL", "MFC - MS 101 LU", "MFC - MS 101 MM",
  "MFC - MS 101 PL", "MFC - MS 101 SH", "MFC - MS 101 SMM", "MFC - MS 101 T",
  "MFC - MS 103 MM", "MFC - MS 103 SMM", "MFC - MS 103 T", "MFC - MS 104 LU",
  "MFC - MS 104 MM", "MFC - MS 104 PL", "MFC - MS 104 SH", "MFC - MS 104 SMM",
  "MFC - MS 104 T", "MFC - MS 105 G", "MFC - MS 106 MM", "MFC - MS 106 PL",
  "MFC - MS 106 SH", "MFC - MS 106 SMM", "MFC - MS 107 SMM", "MFC - MS 120 PL",
  "MFC - MS 201 LU", "MFC - MS 203 LU", "MFC - MS 212 LU", "MFC - MS 215 LU",
  "MFC - MS 216 LU", "MFC - MS 217 LU", "MFC - MS 220-1 LU", "MFC - MS 222 LU",
  "MFC - MS 230 LU",
  "MFC - MS 303 T Ngang", "MFC - MS 309 T Ngang", "MFC - MS 323 T Ngang", "MFC - MS 324 T Ngang",
  "MFC - MS 325 T Ngang", "MFC - MS 328 WG Ngang", "MFC - MS 329 EV Ngang", "MFC - MS 330 PL Ngang",
  "MFC - MS 331 EV Ngang", "MFC - MS 332 RM Ngang", "MFC - MS 333 PL Ngang", "MFC - MS 333 SC Ngang",
  "MFC - MS 334 NV Ngang", "MFC - MS 335 WG Ngang", "MFC - MS 336 WG Ngang", "MFC - MS 337 RM Ngang",
  "MFC - MS 338 RM Ngang", "MFC - MS 338 T Ngang", "MFC - MS 340 T Ngang", "MFC - MS 341 T Ngang",
  "MFC - MS 347 PL Ngang", "MFC - MS 368 T Ngang", "MFC - MS 376 FL Ngang", "MFC - MS 379 ML Ngang",
  "MFC - MS 383 WG Ngang", "MFC - MS 384 T Ngang", "MFC - MS 385 T Ngang", "MFC - MS 386 T Ngang",
  "MFC - MS 388 EV Ngang", "MFC - MS 389 SL Ngang", "MFC - MS 390 EV Ngang", "MFC - MS 401 PL Ngang",
  "MFC - MS 402 PL Ngang", "MFC - MS 403 PL Ngang", "MFC - MS 404 PL Ngang", "MFC - MS 405 PL Ngang",
  "MFC - MS 406 PL Ngang", "MFC - MS 407 PL Ngang", "MFC - MS 408 PL Ngang", "MFC - MS 409 MM Ngang",
  "MFC - MS 410 MM Ngang", "MFC - MS 411 MM Ngang", "MFC - MS 412 MM Ngang", "MFC - MS 413 MM Ngang",
  "MFC - MS 414 MM Ngang", "MFC - MS 415 EV Ngang", "MFC - MS 416 EV Ngang", "MFC - MS 417 EV Ngang",
  "MFC - MS 418 EV Ngang", "MFC - MS 419 RM Ngang", "MFC - MS 420 RM Ngang", "MFC - MS 421 RM Ngang",
  "MFC - MS 422 RM Ngang", "MFC - MS 423 RM Ngang", "MFC - MS 424 RM Ngang", "MFC - MS 425 RL Ngang",
  "MFC - MS 426 SC Ngang", "MFC - MS 427 RL Ngang", "MFC - MS 428 RL Ngang", "MFC - MS 429 RL Ngang",
  "MFC - MS 430 BT Ngang", "MFC - MS 431 BT Ngang", "MFC - MS 432 SC Ngang", "MFC - MS 433 SMM Ngang",
  "MFC - MS 434 SMM Ngang", "MFC - MS 435 SMM Ngang", "MFC - MS 436 SMM Ngang", "MFC - MS 437 SMM Ngang",
  "MFC - MS 439 RL Ngang", "MFC - MS 440 NWG Ngang", "MFC - MS 441 RL Ngang", "MFC - MS 442 RL Ngang",
  "MFC - MS 443 RL Ngang", "MFC - MS 444 RL Ngang", "MFC - MS 445 RL Ngang", "MFC - MS 446 FR Ngang",
  "MFC - MS 447 SL Ngang", "MFC - MS 448 NWG Ngang", "MFC - MS 449 FR Ngang", "MFC - MS 450 FR Ngang",
  "MFC - MS 451 SMM Ngang", "MFC - MS 452 SMM Ngang", "MFC - MS 453 SMM Ngang", "MFC - MS 454 RL Ngang",
  "MFC - MS 455 NWG Ngang", "MFC - MS 456 RM Ngang", "MFC - MS 457 NV Ngang", "MFC - MS 458 XM Ngang",
  "MFC - MS 459 XM Ngang", "MFC - MS 460 XM Ngang", "MFC - MS 461 SC01 Ngang", "MFC - MS 462 SC01 Ngang",
  "MFC - MS 463 SC01 Ngang", "MFC - MS 464 SC01 Ngang", "MFC - MS 465 SC04 Ngang", "MFC - MS 466 SC04 Ngang",
  "MFC - MS 467 SC04 Ngang", "MFC - MS 468 SC02 Ngang", "MFC - MS 469 SC02 Ngang", "MFC - MS 470 SC02 Ngang",
  "MFC - MS 471 SC03 Ngang", "MFC - MS 472 SC03 Ngang", "MFC - MS 473 SC03 Ngang", "MFC - MS 474 SC03 Ngang",
  "MFC - MS 475 NWM Ngang", "MFC - MS 476 SHG Ngang", "MFC - MS 477 NWM Ngang", "MFC - MS 478 SHG Ngang",
  "MFC - MS 479 NWM Ngang", "MFC - MS 480 SHG Ngang", "MFC - MS 481 NWM Ngang", "MFC - MS 482 NWM Ngang",
  "MFC - MS 483 SHG Ngang", "MFC - MS 501 MM Ngang", "MFC - MS 502 MM Ngang", "MFC - MS 503 MM Ngang",
  "MFC - MS 504 MM Ngang", "MFC - MS 505 MM Ngang", "MFC - MS 506 MM Ngang", "MFC - MS 507 MM Ngang",
  "MFC - MS 508 MM Ngang", "MFC - MS 509 MM Ngang", "MFC - MS 511 MM Ngang", "MFC - MS 512 MM Ngang",
  "MFC - MS 513 MM Ngang", "MFC - MS 514 MM Ngang", "MFC - MS 515 MM Ngang", "MFC - MS 516 MM Ngang",
  "MFC - MS 517 MM Ngang", "MFC - MS 518 MM Ngang", "MFC - MS 519 MM Ngang", "MFC - MS 520 MM Ngang",
  "MFC - MS 601 MM Ngang", "MFC - MS 603 MM Ngang", "MFC - MS 604 RM Ngang", "MFC - MS 605 RM Ngang",
  "MFC - MS 608 EV Ngang", "MFC - MS 609 EV Ngang", "MFC - MS 610 RM Ngang", "MFC - MS 611 EV Ngang",
  "MFC - MS 612 EV Ngang", "MFC - MS 613 EV Ngang", "MFC - MS 614 EV Ngang", "MFC - MS 619 EV Ngang",
  "MFC - MS 620 WN Ngang", "MFC - MS 622 RM Ngang", "MFC - MS 623 EV Ngang", "MFC - MS 624 EV copy Ngang",
  "MFC - MS 624 EV Ngang", "MFC - MS 625 T Ngang", "MFC - MS 626 EV Ngang", "MFC - MS 627 EV Ngang",
  "MFC - MS 630 WN Ngang", "MFC - MS 631 EV Ngang", "MFC - MS 635 WN Ngang", "MFC - MS 640 WN Ngang",
  "MFC - MS 641 ML Ngang", "MFC - MS 642 T Ngang", "MFC - MS 643 WN Ngang", "MFC - MS 644 RM Ngang",
  "MFC - MS 650 WN Ngang", "MFC - MS 651 WN Ngang", "MFC - MS 699 EV Ngang", "MFC - MS 720 SH Ngang",
  "MFC - MS 730 SH Ngang", "MFC - MS 739 RM Ngang", "MFC - MS 740 WN Ngang", "MFC - MS 770 SH Ngang",
  "MFC - MS 771 EV Ngang", "MFC - MS 790 SH Ngang", "MFC - MS 851 T Ngang", "MFC - MS 852 T Ngang",
  "MFC - MS 990 T Ngang", "MFC - MS 996 NV Ngang", "MFC - MS 998 EL Ngang", "MFC - MS 999 MM Ngang",
  "MFC - MS 01012 T Ngang", "MFC - MS 4002 SHG Ngang", "MFC - MS 4012 NWM Ngang", "MFC - MS 4028 NWM Ngang",
  "MFC - MS 4029 NWM Ngang", "MFC - MS 4030 NWM Ngang", "MFC - MS 4038 NWM Ngang", "MFC - MS 4502 NWG Ngang",
  "MFC - MS 4601 T Ngang", "MFC - MS 4602 T Ngang", "MFC - MS 9205 S Ngang", "MFC - MS 9222 RM Ngang",
  "MFC - MS 9223 NV Ngang", "MFC - MS 9225 T Ngang", "MFC - MS 9238 WN Ngang", "MFC - MS 9241 ML Ngang",
  "MFC - MS 9284 T Ngang", "MFC - MS 10081 NV Ngang", "MFC - MS 10083 T Ngang", "MFC - MS 10084 T Ngang",
  "MFC - MS LK056 T Ngang", "MFC - MS LK352 T Ngang", "MFC - MS LK452 T Ngang", "MFC - MS LK995 SL Ngang",
  "MFC - MS LK3106 T Ngang", "MFC - MS LK4457 T Ngang", "MFC - MS LK4463 T Ngang", "MFC - MS LK4501 T Ngang",
  "MFC - MS LK4507 T Ngang", "MFC - MS LK9904 T Ngang"
];
